--liquibase formatted sql

--changeset mood:10
CREATE TABLE REFRESH_TOKENS
(
    TOKEN_ID     UUID PRIMARY KEY,
    APP_USER_ID  UUID NOT NULL REFERENCES APP_USERS (APP_USER_ID),
    TOKEN_HASH   VARCHAR(64) NOT NULL UNIQUE,
    EXPIRES_AT   TIMESTAMPTZ NOT NULL,
    REVOKED      BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT   TIMESTAMPTZ NOT NULL
);

--changeset mood:11
CREATE INDEX REFRESH_TOKENS_APP_USER_ID_INDEX ON REFRESH_TOKENS (APP_USER_ID);
